// Initial Catalog Data for Khaista Libaas
const INITIAL_PRODUCTS = [
  {
    id: "kl-001",
    name: "Emerald Royal Embroidered Lawn 3-Piece",
    category: "lawn",
    price: 8990,
    discountPercent: 50, // Default sale offer example
    image: "assets/products/lawn_1.jpg",
    fabric: "Premium Super-Fine Swiss Lawn Shirt, Pure Silk Dupatta, Dyed Cotton Trouser",
    pieces: "3 Piece Unstitched / Custom Stitched",
    color: "Emerald Green & Antique Gold",
    sizes: ["Unstitched", "Small", "Medium", "Large", "Extra Large"],
    description: "Intricately detailed embroidered lawn front with delicate tilla work, paired with a digital printed silk dupatta and dyed trouser.",
    inStock: true,
    isNew: true,
    isBestseller: true
  },
  {
    id: "kl-002",
    name: "Blush Chiffon Festive Luxury Suit",
    category: "chiffon",
    price: 14500,
    discountPercent: 30,
    image: "assets/products/chiffon_1.jpg",
    fabric: "Hand-Embroidered Chiffon Shirt, Organza Dupatta with Pearl Borders, Raw Silk Trouser",
    pieces: "3 Piece Stitched Luxury Pret",
    color: "Blush Pink & Rose Gold",
    sizes: ["Small", "Medium", "Large", "Extra Large"],
    description: "Exquisite chiffon dress embellished with pearls, sequins, and rose gold threadwork. Perfect for weddings and festive occasions.",
    inStock: true,
    isNew: true,
    isBestseller: true
  },
  {
    id: "kl-003",
    name: "Imperial Navy Velvet Zari Edition",
    category: "velvet",
    price: 16990,
    discountPercent: 50,
    image: "assets/products/velvet_1.jpg",
    fabric: "Micro-Velvet 9000 Shirt with Heavy Zari Border, Heavy Velvet Shawl Dupatta, Silk Pants",
    pieces: "3 Piece Stitched Winter Velvet",
    color: "Royal Navy Blue & Gold",
    sizes: ["Small", "Medium", "Large"],
    description: "Opulent micro-velvet ensemble featuring traditional gold zardozi embroidery and an ultra-rich velvet embroidered shawl.",
    inStock: true,
    isNew: false,
    isBestseller: true
  },
  {
    id: "kl-004",
    name: "Burgundy Bridal Anarkali Gown",
    category: "festive",
    price: 24990,
    discountPercent: 15,
    image: "assets/hero_1.jpg",
    fabric: "Luxury Pure Net & Chiffon Gown, Heavy Dupatta, Silk Under-slip & Chooridar",
    pieces: "3 Piece Stitched Festive Wear",
    color: "Deep Burgundy & Rose Gold",
    sizes: ["Small", "Medium", "Large"],
    description: "Formal floor-length royal flared Anarkali featuring dense intricate metallic rose gold tilla and sequin hand embroidery.",
    inStock: true,
    isNew: true,
    isBestseller: false
  },
  {
    id: "kl-005",
    name: "Dusty Rose Printed Lawn 3-PC",
    category: "lawn",
    price: 6990,
    discountPercent: 30,
    image: "assets/products/chiffon_1.jpg",
    fabric: "Digital Printed Lawn Shirt, Chiffon Dupatta, Cambric Trouser",
    pieces: "3 Piece Unstitched",
    color: "Dusty Rose & Cream",
    sizes: ["Unstitched", "Small", "Medium", "Large"],
    description: "Vibrant summer digital lawn suit inspired by royal floral gardens with a lightweight breathable chiffon dupatta.",
    inStock: true,
    isNew: true,
    isBestseller: false
  },
  {
    id: "kl-006",
    name: "Mustard Silk Embroidered Pret Kurti",
    category: "pret",
    price: 4990,
    discountPercent: 15,
    image: "assets/products/lawn_1.jpg",
    fabric: "Raw Silk Shirt with Lace & Organza Sleeve Detailing",
    pieces: "1 Piece Ready-to-Wear Shirt",
    color: "Mustard Gold & Pearl",
    sizes: ["Small", "Medium", "Large", "Extra Large"],
    description: "Modern minimalist luxury pret kurti with delicate pearl buttons and scalloped organza cuffs for daily elegance.",
    inStock: true,
    isNew: false,
    isBestseller: true
  },
  {
    id: "kl-007",
    name: "Midnight Black Embroidered Chiffon",
    category: "chiffon",
    price: 13990,
    discountPercent: 50,
    image: "assets/products/velvet_1.jpg",
    fabric: "Pure Chiffon Front-Open Shirt, Embroidered Net Dupatta, Grip Silk Trousers",
    pieces: "3 Piece Stitched Pret",
    color: "Midnight Black & Silver Zari",
    sizes: ["Small", "Medium", "Large"],
    description: "Sophisticated black chiffon evening dress adorned with silver thread embroidery and organza borders.",
    inStock: true,
    isNew: false,
    isBestseller: false
  },
  {
    id: "kl-008",
    name: "Teal Green Silk Unstitched Suit",
    category: "unstitched",
    price: 7990,
    discountPercent: 0,
    image: "assets/products/lawn_1.jpg",
    fabric: "Silk Lawn Shirt, Organza Embroidered Dupatta, Dyed Trouser",
    pieces: "3 Piece Unstitched Collection",
    color: "Teal Green & Bronze",
    sizes: ["Unstitched"],
    description: "Unstitched luxury 3-piece suit featuring embroidered neckline patch, sleeve borders, and contrast printed dupatta.",
    inStock: true,
    isNew: true,
    isBestseller: false
  }
];
